/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/builder': RouteRecordInfo<'/builder', '/builder', Record<never, never>, Record<never, never>>,
    '/builds': RouteRecordInfo<'/builds', '/builds', Record<never, never>, Record<never, never>>,
    '/cart': RouteRecordInfo<'/cart', '/cart', Record<never, never>, Record<never, never>>,
    '/categories': RouteRecordInfo<'/categories', '/categories', Record<never, never>, Record<never, never>>,
    '/category-detail': RouteRecordInfo<'/category-detail', '/category-detail', Record<never, never>, Record<never, never>>,
    '/checkout': RouteRecordInfo<'/checkout', '/checkout', Record<never, never>, Record<never, never>>,
    '/create-post': RouteRecordInfo<'/create-post', '/create-post', Record<never, never>, Record<never, never>>,
    '/delete': RouteRecordInfo<'/delete', '/delete', Record<never, never>, Record<never, never>>,
    '/events': RouteRecordInfo<'/events', '/events', Record<never, never>, Record<never, never>>,
    '/karts': RouteRecordInfo<'/karts', '/karts', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/my-designs': RouteRecordInfo<'/my-designs', '/my-designs', Record<never, never>, Record<never, never>>,
    '/part-description': RouteRecordInfo<'/part-description', '/part-description', Record<never, never>, Record<never, never>>,
    '/part-detail': RouteRecordInfo<'/part-detail', '/part-detail', Record<never, never>, Record<never, never>>,
    '/parts': RouteRecordInfo<'/parts', '/parts', Record<never, never>, Record<never, never>>,
    '/post-detail': RouteRecordInfo<'/post-detail', '/post-detail', Record<never, never>, Record<never, never>>,
    '/posts': RouteRecordInfo<'/posts', '/posts', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/rating-card': RouteRecordInfo<'/rating-card', '/rating-card', Record<never, never>, Record<never, never>>,
    '/save': RouteRecordInfo<'/save', '/save', Record<never, never>, Record<never, never>>,
    '/supplier-panel': RouteRecordInfo<'/supplier-panel', '/supplier-panel', Record<never, never>, Record<never, never>>,
    '/warning': RouteRecordInfo<'/warning', '/warning', Record<never, never>, Record<never, never>>,
    '/xp-level-up': RouteRecordInfo<'/xp-level-up', '/xp-level-up', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/about.vue': {
      routes: '/about'
      views: never
    }
    'src/pages/admin.vue': {
      routes: '/admin'
      views: never
    }
    'src/pages/builder.vue': {
      routes: '/builder'
      views: never
    }
    'src/pages/builds.vue': {
      routes: '/builds'
      views: never
    }
    'src/pages/cart.vue': {
      routes: '/cart'
      views: never
    }
    'src/pages/categories.vue': {
      routes: '/categories'
      views: never
    }
    'src/pages/category-detail.vue': {
      routes: '/category-detail'
      views: never
    }
    'src/pages/checkout.vue': {
      routes: '/checkout'
      views: never
    }
    'src/pages/create-post.vue': {
      routes: '/create-post'
      views: never
    }
    'src/pages/delete.vue': {
      routes: '/delete'
      views: never
    }
    'src/pages/events.vue': {
      routes: '/events'
      views: never
    }
    'src/pages/karts.vue': {
      routes: '/karts'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/my-designs.vue': {
      routes: '/my-designs'
      views: never
    }
    'src/pages/part-description.vue': {
      routes: '/part-description'
      views: never
    }
    'src/pages/part-detail.vue': {
      routes: '/part-detail'
      views: never
    }
    'src/pages/parts.vue': {
      routes: '/parts'
      views: never
    }
    'src/pages/post-detail.vue': {
      routes: '/post-detail'
      views: never
    }
    'src/pages/posts.vue': {
      routes: '/posts'
      views: never
    }
    'src/pages/profile.vue': {
      routes: '/profile'
      views: never
    }
    'src/pages/rating-card.vue': {
      routes: '/rating-card'
      views: never
    }
    'src/pages/save.vue': {
      routes: '/save'
      views: never
    }
    'src/pages/supplier-panel.vue': {
      routes: '/supplier-panel'
      views: never
    }
    'src/pages/warning.vue': {
      routes: '/warning'
      views: never
    }
    'src/pages/xp-level-up.vue': {
      routes: '/xp-level-up'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
